apiVersion: v1
kind: Service
metadata:
  labels:
    module: apicurio-studio-api
  name: apicurio-studio-api
spec:
  ports:
  - name: "8091"
    port: 8091
    targetPort: 8080
  selector:
    module: apicurio-studio-api
---
apiVersion: v1
kind: Service
metadata:
  labels:
    module: apicurio-studio-ui
  name: apicurio-studio-ui
spec:
  ports:
  - name: "8093"
    port: 8093
    targetPort: 8080
  selector:
    module: apicurio-studio-ui
---
apiVersion: v1
kind: Service
metadata:
  labels:
    module: apicurio-studio-ws
  name: apicurio-studio-ws
spec:
  ports:
  - name: "8092"
    port: 8092
    targetPort: 8080
    protocol: TCP
  selector:
    module: apicurio-studio-ws
---
apiVersion: v1
kind: Service
metadata:
  labels:
    module: apicurio-studio-db
  name: apicuriodb
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    module: apicurio-studio-db

