apiVersion: v1
kind: ConfigMap
metadata:
  name: apicurio-configmap
data:
  keycloak-url:  http://KEYCLOAK_URL/auth
  apicurio-ui-logout-redirect-uri: /
  apicurio-ui-hub-api-url: http://APICURIO_URL/studio-api
  apicurio-ui-editing-url: ws://APICURIO_URL/ws
  apicurio-microcks-api-url:  http://MICROCKS_URL/api
  apicurio-db-connection-url: jdbc:mysql://apicuriodb:3306/apicuriodb
  apicurio-kc-client-id: apicurio-studio
  apicurio-kc-realm: Apicurio
  apicurio-microcks-client-id: microcks-serviceaccount
  apicurio-ui-feature-share-with-everyone: "true"
  apicurio-ui-feature-microcks: "false"
