language: java

before_cache:
  - "rm -rf $HOME/.m2/repository/io/apicurio"

cache:
  yarn: true
  directories:
    - "$TRAVIS_BUILD_DIR/front-end/app/node_modules" # NPM/Yarn
    - "$HOME/.m2" # Maven

before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
  - echo 'MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1 -Xmx512m"' > ~/.mavenrc

jdk:
  - oraclejdk8
      
script:
  - mvn clean install
