version: '3'

volumes:
  mysql_apicurio2:

services:

  apicurio-studio-mysql:
    image: 'percona:5.7'
    command: [
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]
    environment:
      MYSQL_DATABASE: ${AS_MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${AS_MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${AS_MYSQL_USER}
      MYSQL_PASSWORD: ${AS_MYSQL_PASSWORD}
    volumes:
      - 'mysql_apicurio2:/var/lib/mysql'


  apicurio-studio-ws:
    image: 'apicurio/apicurio-studio-ws:0.2.25.Final'
    depends_on: [apicurio-studio-mysql]
    ports:
      - '8092:8080'
    environment:
      JAVA_TOOL_OPTIONS: '-Djava.net.preferIPv4Stack=true'

      APICURIO_DB_TYPE: ${APICURIO_DB_TYPE}
      APICURIO_DB_DRIVER_NAME: ${APICURIO_DB_DRIVER_NAME}
      APICURIO_DB_CONNECTION_URL: ${APICURIO_DB_CONNECTION_URL}
      APICURIO_DB_USER_NAME: ${APICURIO_DB_USER_NAME}
      APICURIO_DB_PASSWORD: ${APICURIO_DB_PASSWORD}
      APICURIO_DB_INITIALIZE: ${WS_APICURIO_DB_INITIALIZE}


  apicurio-studio-api:
    image: 'apicurio/apicurio-studio-api:0.2.25.Final'
    depends_on: [apicurio-studio-mysql, apicurio-studio-ws]
    ports:
      - '8091:8080'
    environment:
      JAVA_TOOL_OPTIONS: '-Djava.net.preferIPv4Stack=true'

      APICURIO_KC_AUTH_URL: ${APICURIO_KC_AUTH_URL}

      APICURIO_DB_TYPE: ${APICURIO_DB_TYPE}
      APICURIO_DB_DRIVER_NAME: ${APICURIO_DB_DRIVER_NAME}
      APICURIO_DB_CONNECTION_URL: ${APICURIO_DB_CONNECTION_URL}
      APICURIO_DB_USER_NAME: ${APICURIO_DB_USER_NAME}
      APICURIO_DB_PASSWORD: ${APICURIO_DB_PASSWORD}
      APICURIO_DB_INITIALIZE: ${API_APICURIO_DB_INITIALIZE}

      APICURIO_MICROCKS_API_URL: ${APICURIO_MICROCKS_API_URL}
      APICURIO_MICROCKS_CLIENT_ID: ${APICURIO_MICROCKS_CLIENT_ID}
      APICURIO_MICROCKS_CLIENT_SECRET: ${APICURIO_MICROCKS_CLIENT_SECRET}

      APICURIO_GITHUB_API_URL: ${APICURIO_GITHUB_API_URL}
      APICURIO_GITLAB_API_URL: ${APICURIO_GITLAB_API_URL}
      APICURIO_BITBUCKET_API_URL: ${APICURIO_BITBUCKET_API_URL}


  apicurio-studio-ui:
    image: 'apicurio/apicurio-studio-ui:0.2.25.Final'
    depends_on: [apicurio-studio-mysql, apicurio-studio-api, apicurio-studio-ws]
    ports:
      - '8093:8080'
    environment:
      JAVA_TOOL_OPTIONS: '-Djava.net.preferIPv4Stack=true'

      APICURIO_KC_AUTH_URL: ${APICURIO_KC_AUTH_URL}
      APICURIO_UI_HUB_API_URL: ${APICURIO_UI_HUB_API_URL}
      APICURIO_UI_EDITING_URL: ${APICURIO_UI_EDITING_URL}
      APICURIO_UI_FEATURE_MICROCKS: ${APICURIO_UI_FEATURE_MICROCKS}
